const imagesPath = {
    logo: require('../assets/logo.png'),
    walkthrough1: require('../assets/boarding1.png'),
    walkthrough2: require('../assets/boarding2.png'),
    walkthrough3: require('../assets/boarding3.png'),
    robot: require('../assets/robot.png'),
    recaptcha: require('../assets/recaptcha.png'),
    gallery: require('../assets/gallery.png'),
    cloudPlus: require('../assets/cloud_plus.png'),
    avatarSample: require('../assets/avatar_sample.png'),
    avatar1: require('../assets/avatar1.png'),
    avatar2: require('../assets/avatar2.png'),
    avatar3: require('../assets/avatar3.png'),
    avatar4: require('../assets/avatar4.png'),
    avatar5: require('../assets/avatar5.png'),
    avatar6: require('../assets/avatar6.png'),
    avatar7: require('../assets/avatar7.png'),
    avatar8: require('../assets/avatar8.png'),
    resend: require('../assets/resend.png'),
    //tabs
    home: require('../assets/home.png'),
    lists: require('../assets/lists.png'),
    add: require('../assets/add.png'),
    share: require('../assets/share.png'),
    discover: require('../assets/discover.png'),
    //home
    restaurant: require('../assets/restaurant.png'),
    wine: require('../assets/wine.png'),
    bourbon: require('../assets/bourbon.png'),
    movies: require('../assets/movies.png'),
    tvShows: require('../assets/tv_shows.png'),
    podcasts: require('../assets/podcasts.png'),
    movie: require('../assets/movie.png'),
    watch: require('../assets/watch.png'),
    filter: require('../assets/filter.png'),
    favorite: require('../assets/favorite.png'),
    search: require('../assets/search.png'),
    addImage: require('../assets/add_image.png'),
    camera: require('../assets/camera.png'),
    eye_open: require('../assets/eye_open.png'),
    edit: require('../assets/edit.png'),
    delete: require('../assets/delete.png'),
    list_icon1: require('../assets/list_icon1.png'),
    list_icon2: require('../assets/list_icon2.png'),
    list_icon3: require('../assets/list_icon3.png'),
    list_icon4: require('../assets/list_icon4.png'),
    list_icon5: require('../assets/list_icon5.png'),
    list_icon6: require('../assets/list_icon6.png'),
    list_icon7: require('../assets/list_icon7.png'),
    calender: require('../assets/calender.png'),
    sortStatus: require('../assets/sort_status.png'),
    sortFavorite: require('../assets/sort_favorite.png'),
    noInternet: require('../assets/no_internet.png'),
}

export default imagesPath