export const STRINGS = {
  TITLES: {
    appName: 'listkeepr',
    itemDetails: 'Item Details',
  },
  LABELS: {
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    submit: 'Submit',
    success: 'success',
    error: 'error',
    firstname: 'First Name',
    lastname: 'Last Name',
    emailAddress: 'Email Address (Username)',
    emailPlaceholderText: 'ex: johndoe@email.com',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    password: 'Password',
    rememberMe: 'Remember me',
    name: 'Name',
    title: 'Title',
    seriesTitle: 'Series Title',
    episodeTitle: 'Episode Title',
    year: 'Year',
    imageUrl: 'Image URL',
    location: 'Location',
    brewery: 'Brewery',
    typeSomethingHere: 'Type something here...',
    enterImageUrl: 'Enter image URL',
    recommendedBy: 'Recommended By',
    recommendedByPlaceholder: 'ex: name',
    notes: 'Notes',
    typeSomething: 'type something...',
    listName: 'List Name',
    listNamePlaceholder: 'e.g. Stand-up Specials',
    selectIcon: 'Select Icon',
    savedForLater: 'Saved for Later',
    author: 'Author',
    podcastsType: 'Podcasts Type',
    rating: 'Rating',
    releaseDate: 'Release Date',
  },
  ONBOARDING: {
    title1: 'Save what you love',
    subtitle1: 'Restaurants, wine, bourbon, movies, shows, podcasts, and books — every favorite and recommendation safe in one spot.',
    title2: 'Everything remembered',
    subtitle2: 'Lists that catch every must-try and already-loved item, so it’s there the instant you need it.',
    title3: 'Add in a tap, find in a flash',
    subtitle3: 'Capture new items in seconds — so you’re back to eating, sipping, or reading.',
  },
  RECAPTCHA: {
    title: 'Just making sure you’re a real memory-keeper!',
    subtitle: 'We need to make sure you’re not a robot. It only takes a second!',
    notRobotText: 'I\'m not a robot',
    privacyTerms: 'Privacy - Terms'
  },
  SIGNUP: {
    title: 'Let\'s get you saving!',
    subTitle: 'You’re just a few steps away from keeping every must-try and already-loved item in one place.',
    addImageTitle: 'Add a little personality',
    addImageSubTitle: 'Choose a photo or snap one now.',
    loaderText: 'Please wait...',
  },
  LOGIN: {
    title: 'Welcome back, memory-keeper 👋',
    subtitle: 'Log in to pick up where you left off.',
  },
  FORGOT_PASSWORD: {
    title: 'No worries, it happens.',
    subtitle: 'Let’s get you back in.',
    sendResetLink: 'We’ll send you a link to reset your password.',
    resetLoaderText: 'Sending reset link...',
    sentResetLinkToast: 'We’ve sent a reset link to your inbox. Check your email to get started.',
  },
  UPDATE_PASSWORD: {
    title: 'Secure Your listkeepr',
    subTitle: 'A new password to protect what you love.',
  },
  CHANGE_PASSWORD: {
    title: 'Change Password',
    subTitle: 'A new password to protect what you love.',
  },
  VALIDATIONS: {
    passwordMismatch: 'Password mismatch',
    passwordMatched: 'Password matched',
    signupLoaderText: 'Please wait...',
    loginLoaderText: 'Bringing back your memories...',
    updatePasswordSuccess: 'All set! Your listkeepr is now more secure.',
    currentPasswordWrong:'Current password is wrong',
    changePasswordSuccess: 'Congratulations! your password has been changed successfully. Kindly login again',
    areYouSureWantToDelete:'Are you sure want to delete?',
  },
  BUTTONS: {
    getStarted: 'Get Started',
    next: 'Next',
    skip: 'Skip',
    login: 'Login',
    logout: 'Logout',
    signup: 'Sign Up',
    signin: 'Sign In',
    linkSent: 'Link Sent',
    sendResetLink: 'Send Reset Link',
    backToSignIn: 'Back to Sign In',
    forgotPassword: 'Forgot Password?',
    updatePassword: 'Update Password',
    saveList: 'Save List',
    updateList: 'Update List',
    addYourFirst: 'Add your first',
    saveItemToTheList: 'Save Item to the list',
    updateItemToTheList: 'Update Item to the list',
    applyFilters: 'Apply Filters',
    clearFilters: 'Clear Filters',
    yes:'Yes',
    no: 'No',
  },
  MISC: {
    passwordContainsText: 'Your password must contain:',
    charactersLimit: 'At least 8 characters',
    uppercaseLetter: 'One uppercase letter',
    lowercaseLetter: 'One lowercase letter',
    oneNumber: 'One number',
    onSymbol: 'One symbol (like !, @, #, $)',
    signupAgreeText: 'By signing up, you agree to our',
    termsConditions: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    alreadyAccount: 'Already have a listkeepr account?',
    newHere: 'New here?',
    quickAndFree: 'it’s quick and free.',
    notGetEmail: 'Didn’t get the email?',
    resendIt: 'Resend It',
    changeMind: 'Changed your mind?',
    somethingWentWrong: 'Something went wrong. Try again.',
    unableToResend: 'Unable to resend. Try again.',
    isFirstTime: '0',
    addItem: 'Add Item',
    yourLists: 'Your Lists',
    viewList: 'View List',
    editList: 'Edit List',
    deleteList: 'Delete List',
    addNewList: 'Add New List',
    editItem: 'Edit Item',
    deleteItem: 'Delete Item',
    listAddedSuccessfully: 'List added successfully!',
    listUpdatedSuccessfully: 'List updated successfully!',
    listDeletedSuccessfully: 'List deleted successfully!',
    itemAddedSuccessfully: 'Item added successfully!',
    itemUpdatedSuccessfully: 'Item updated successfully!',
    itemDeletedSuccessfully: 'Item deleted successfully!',
    totalItems: 'Total Items',
    sortBy: 'Sort By',
    filterBy: 'Filter By',
    noItemsTitle: 'No items!',
    noItemsSubtitle: 'You haven’t added any items to this list.',
    dateAdded: 'Date Added',
    ratingHighLow: 'Rating (High → Low)',
    titleAtoZ: 'Title (A-Z)',
    statusToWatchOrWatched: 'Status (To Watch, Watched)',
    categories: 'Categories',
    status: 'Status',
    oops: 'Oops!',
    comingSoon: 'Coming Soon...',
    somethingWentWrongWhileLoading: 'Something went wrong while loading your lists.',
    tryAgain: 'Try again',
    toWatch: 'To Watch',
    watched: 'Watched',
    toRead: 'To Read',
    read: 'Read',
    toListen: 'To Listen',
    listen: 'Listened',
    notTried: 'Not Tried',
    tried: 'Tried',
    wantToVisit: 'Want to Visit',
    visited: 'Visited',
    notCompleted: 'Not Completed',
    complete: 'Complete',
    series: 'Series',
    episode: 'Episode',
    //sort by
    sortDate: '&order=created_at.desc',
    sortRating: '&order=rating.desc',
    sortTitle: '&order=title.asc',
    sortStatus: '&order=status.asc',
    sortSaveForLater: '&order=save_for_later',
    //filter by
    filterToWatch: 'to_watch',
    filterWatched: 'watched',
    filterToRead: 'to_read',
    filterRead: 'read',
    filterToListen: 'to_listen',
    filterListened: 'listened',
    filterNotTried: 'not_tried',
    filterTried: 'tried',
    filterWantToVisit: 'want_to_visit',
    filterVisited: 'visited',
    filterNotCompleted: 'not_completed',
    filterComplete: 'complete',
    filterSeries: 'series',
    filterEpisode: 'episode',
    //list types labels
    books: 'books',
    podcasts: 'podcasts',
    bourbon: 'bourbon',
    wine: 'wine',
    restaurants: 'restaurants',
    tvShows: 'tv shows',
    beer: 'beer',
    movies: 'movies',
  }
};

// Route Names
export const ROUTES = {
  splash: "Splash",
  Onboarding: "Onboarding",
  recaptcha: 'recaptcha',
  signup: "Signup",
  login: "Login",
  forgotPassword: "ForgotPassword",
  updatePassword: "updatePassword",

  //main
  main: "Main",
  mainHome: "MainHome",
  mainLists: "MainLists",
  mainAdd: "MainAdd",
  home: "Home",
  lists: "Lists",
  add: "Add",
  share: "Share",
  discover: "Discover",
  quickAdd: "QuickAdd",
  profileScreen: "Profile",
  changePasswordScreen: "ChangePasswordScreen",
  listDetailsScreen: 'ListDetailsScreen',
  itemDetailsScreen: 'ItemDetailsScreen',
  editItemScreen: 'EditItemScreen',
};