export default {
    LOGIN: "LOGIN",
    SIGNUP:"SIGNUP",
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    IS_DEMO:"IS_DEMO",
    CHANGE_APP_THEME:"CHANGE_APP_THEME",
    CHANGE_APP_LANGUAGE:"CHANGE_APP_LANGUAGE",
    CHANGE_LOGIN_TYPE:"CHANGE_LOGIN_TYPE",
    NO_INTERNET:"NO_INTERNET",

    //HOME
    MEDICAL_SPECIALITY_LIST:"MEDICAL_SPECIALITY_LIST",
    LANGUAGE_LIST:"LANGUAGE_LIST",
}